# Generated by Django 6.0.4 on 2026-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherreading",
            name="temperatureMax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherreading",
            name="temperatureMin",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
