# Generated by Django 6.0.4 on 2026-04-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_weatherreading_temperaturemax_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherreading",
            name="temperatureMax",
        ),
        migrations.RemoveField(
            model_name="weatherreading",
            name="temperatureMin",
        ),
    ]
